services:
  seanime:
    image: umagistr/seanime:latest-rootless
    container_name: seanime
    # user: "1000:1500"  # Optional: override UID:GID (default is 1000:1000)
    ports:
      - "3211:43211"
    volumes:
      - ./seanime-config:/home/seanime/.config/Seanime
      - ./anime:/anime
      - ./downloads:/downloads
    restart: unless-stopped
